import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";
import { TopNav } from "./_components/topnav";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/providers/theme-provider";

export const metadata = {
  title: "Translucent Detyre",
  description: "Generated by @demarchenac",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log({ font: GeistSans.variable });

  return (
    <ClerkProvider
      localization={esES}
      appearance={{ elements: { footer: "hidden" } }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "bg-background flex h-screen min-h-screen flex-col gap-4 font-sans antialiased",
            `${GeistSans.variable}`,
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TopNav />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
